version: '3.3'
services:
  mysql-database:
    image: mysql:8
    ports:
      - 3306:3306
    volumes:
      - C:\Users\Fabio\Documents\docker-volumes\mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: test
  backend:
    image: fabiopulcinelli/testdocker:9.0
    ports:
      - 8080:8080
    environment:
      DB_URL: jdbc:mysql://mysql-database:3306/test
      DB_USERNAME: root
      DB_PASSWORD: password
    depends_on:
      - mysql-database
  frontend:
    image: testdockerangular:6.0
    ports:
      - 81:80